apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: {{ .Values.app.service.port }}
    protocol: TCP
    targetPort: {{ .Values.app.service.targetPort }}
  type: NodePort

