apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceEstimator.name }}
  namespace: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: {{ .Values.app.serviceEstimator.port }}
    protocol: TCP
    targetPort: {{ .Values.app.serviceEstimator.targetPort }}
  type: NodePort